config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations',
                                    passwords: 'users/passwords',
                                    invitations: 'users/invitations',
                                    confirmation: 'users/confirmation' }
  get 'home/index'
  get 'more_events' => 'home#more_events'
  resources :resources

  root 'home#index'

  get 'contact', to: 'contact#new'
  post 'contact', to: 'contact#create', as: 'save_contact'
  get 'contact/zoho', to: 'contact#zoho_contact'
  get 'connect_with_meetup', to: 'home#connect_with_meetup', as: :connect_with_meetup
  get '/oauth2/meetup_api', to: 'oauth2#meetup_api'

end

app/views/resources/_form.html.erb
<%= form_for(@resource) do |f| %>
<div class="row">
  <div class="col-md-6">
    <div class="form-group required">
      <label for="resource_title">Title <span class="text-red">*</span></label><br>
      <%= f.text_field :title, class: 'form-control'%>
      <span class="text-red"><%=  show_errors(@resource, :title)%></span>
    </div>
    <div class="form-group">
      <label for="resource_description">Description</label><br>
      <%= f.text_area :description, class: 'form-control' %>
    </div>
    <div class="form-group required">
      <label for="resource_link_name">Link Name <span class="text-red">*</span></label><br>
      <%= f.text_field :link_name, class: 'form-control'%>
      <span class="text-red"><%=show_errors(@resource, :link_name)%></span>
    </div>
    <div class="form-group required">
      <label for="resource_link_uri">Link URL <span class="text-red">*</span></label><br>
      <%= f.text_field :link_uri, class: 'form-control'%>
      <span class="text-red"><%= show_errors(@resource, :link_uri)%></span>
    </div>
    <div class="form-group">
      <label for="resource_image">Image</label><br>
      <% if controller.action_name == "edit" %>
        <%= image_tag @resource.image.thumb.url || 'no-image.png', class: 'img-thumbnail', id: 'image' %>
      <%else%>
        <%= image_tag @resource.image.thumb.url || 'no-image-flat.png', class: 'img-thumbnail', id: 'image' %>
      <%end%>
      <div>
        <%= f.label :image, class: 'btn btn-success browse-btn' do %><i class="fa fa-picture-o mar-right-6" aria-hidden="true"></i> Choose File
        <%= f.file_field :image, style: "display:none;" %>
      </div>
      <span class="text-red"><%= show_errors(@resource, :image)%></span>
      <% end %>
    </div>
    <div class="form-group">
      <%= button_tag class: 'btn gold-btn btn-lg', type: 'submit' do %><i class="fa fa-check" aria-hidden="true"></i> Submit<% end %>
    </div>
  </div>
</div>
<% end %>


<script>
  $(document).ready(function () {
    $("#resource_image").on('change',function (e) {
      var file = this.files[0];
      var reader = new FileReader();
      reader.onload = function (e) {
        $("#image").attr('src', e.target.result);
        $("#resource_image").attr('src', e.target.result);
      };
      reader.readAsDataURL(file);
    });
  });
</script>

app/views/resources/edit.html.erb
<section class="top-bg">
  <div class="top-bg-inner">
    <div class="container">
      <div class="breadcrumb-top">
        <ol class="breadcrumb white">
          <li><%= link_to 'Home',root_url %></li>
          <li><%= link_to 'Resources', resources_url %></li>
          <li class="active"><%= @resource.title.present? ? @resource.title : @resource.id %></li>
          <li class="active">Edit</li>
        </ol>
      </div>
    </div>
  </div>
</section>
<div class="container page-body">
  <div class="row">
    <div class="col-xs-12">
      <div class="admin-body">
        <h1>Editing <%= @resource.title %></h1>
        <div class="mar-top-30 mar-btm-30">
          <%= render "form" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/resources/index.html.erb
<section class="top-bg">
  <div class="top-bg-inner">
    <div class="container">
      <div class="breadcrumb-top">
        <ol class="breadcrumb white">
          <li><%= link_to 'Home', root_path %></li>
          <li class="active">Resources</li>
        </ol>
      </div>
    </div>
  </div>
</section>
<div class="container page-body resources-listing">
  <div class="row">
    <div class="col-xs-12">
      <h1>BACOMM Resources</h1>
      <% if current_user %>
      <span class="btn-span add-resource pull-right">
        <%= link_to new_resource_path, class: 'btn gold-btn' do %>
          <i class="fa fa-plus" aria-hidden="true"></i> New
        <% end %>
      </span>
      <%= render 'shared/flash' if flash[:success].present? %>
      <% end %>
      <% if @resources.present? %>
        <div class="list-group">
          <% @resources.each do |resource| %>
            <div class="list-group-item resources-data">
              <div class="row">
                <div class="col-md-2 col-sm-3">
                  <%= image_tag resource.image.thumb.url || 'no-img_150.png', class: 'resource-img', alt: resource.title %>
                </div>
                <div class="col-md-10 col-sm-9">
                  <h4><%= resource.title %></h4>
                  <p><span><%= resource.description %></span></p>
                  <%= link_to resource.link_uri, target: '_blank', class: 'btn gold-btn' do %>
                    <i class="fa fa-download fa-lg" aria-hidden="true"></i> <%= resource.link_name %>
                  <% end %>
                  <% if current_user %>
                    <%= link_to edit_resource_path(resource), class: 'btn btn-success', title: 'Edit' do %>
                      <i class="fa fa-pencil" aria-hidden="true"></i> Edit
                    <% end %>
                    <%= link_to resource_path(resource), method: :delete, data: { confirm: 'Are you sure you wish to delete this Resource? This CANNOT be undone.' }, class: 'btn btn-danger', title: 'Delete' do %>
                      <i class="fa fa-trash" aria-hidden="true"></i> Delete
                    <% end %>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      <% else %>
        <div class="col-xs-12 msg-content text-center">
          <h3>No resources found</h3>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/resources/new.html.erb
<section class="top-bg">
  <div class="top-bg-inner">
    <div class="container">
      <div class="breadcrumb-top">
        <ol class="breadcrumb white">
          <li><%= link_to 'Home',root_url %></li>
          <li><%= link_to 'Resources', resources_url %></li>
          <li class="active">New</li>
        </ol>
      </div>
    </div>
  </div>
</section>
<div class="container page-body">
  <div class="row">
    <div class="col-xs-12">
      <div class="admin-body">
        <h1>New Resource</h1>
        <div class="mar-top-30 mar-btm-30">
          <%= render "form" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/resources/show.html.erb
<section class="top-bg">
  <div class="top-bg-inner">
    <div class="container">
      <div class="breadcrumb-top">
        <ol class="breadcrumb white">
          <li><%= link_to 'Home', root_url %></li>
          <li><%= link_to 'Resources', resources_url %></li>
          <li class="active">Show</li>
        </ol>
      </div>
    </div>
  </div>
</section>
<div class="container page-body">
  <div class="msg"><%= render 'shared/flash' if flash[:success].present? %></div>
  <div class="row">
    <div class="col-xs-12">
      <div class="admin-body">
        <h1>Resource</h1>
        <div class="mar-top-30 mar-btm-30 preview-resource">
          <dl class="dl-horizontal">
            <dt>Title:</dt>
            <dd><%= @resource.title %></dd>
            <dt>Description:</dt>
            <dd><%= @resource.description %></dd>
            <dt>Link Name:</dt>
            <dd><%= @resource.link_name %></dd>
            <dt>Link URL:</dt>
            <dd class="wrd-brk"><%= @resource.link_uri %></dd>
            <dt>Image:</dt>
            <dd><%= image_tag @resource.image.thumb.url || 'no-img_150.png', class: 'img-thumbnail', style:'max-width:100px' %></dd>
          </dl>
          <%= link_to 'Edit', edit_resource_path(@resource), class: 'btn gold-btn' %>
          <%= link_to 'Back', resources_path, class: 'btn blue-btn btn-back' %>
        </div>
      </div>
    </div>
  </div>
</div>