config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations',
                                    passwords: 'users/passwords',
                                    invitations: 'users/invitations',
                                    confirmation: 'users/confirmation' }
  get 'home/index'
  get 'more_events' => 'home#more_events'
  resources :resources

  root 'home#index'

  get 'contact', to: 'contact#new'
  post 'contact', to: 'contact#create', as: 'save_contact'
  get 'contact/zoho', to: 'contact#zoho_contact'
  get 'connect_with_meetup', to: 'home#connect_with_meetup', as: :connect_with_meetup
  get '/oauth2/meetup_api', to: 'oauth2#meetup_api'

end

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <div class="col-sm-6 col-xs-12 links-1">
        <ul class="list-inline">
          <li>
            <a href="mailto:info@tomwilsonproperties.com">
            <span aria-hidden="true" class="fa fa-envelope-o"></span>
            info@tomwilsonproperties.com
            </a>
          </li>
          <li><span class="fa fa-phone"></span>408-867-1867</li>
        </ul>
      </div>
      <div class="col-sm-6 col-xs-12 text-right">
        <ul class="list-inline">
          <li>
          <a href="http://www.tomwilsonproperties.com" target="_blank">
            <span class="fa fa-globe"></span>
            www.tomwilsonproperties.com
            </a>
          </li>
          <li><span class="fa fa-map-marker"></span>Saratoga, CA</li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <%= link_to root_path, class:'navbar-brand' do %>
        <%= image_tag "bacomm-logo_small.png", class: 'img-responsive', alt: 'Logo', title: 'BACOMM!' %>
      <% end %>
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Resources', resources_url %></li>
        <li><%= link_to 'Contact Us', contact_url %></li>
        <% if current_user %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Add Resources', new_resource_path %></li>
              <li><%= link_to 'Connect with Meetup', connect_with_meetup_path, method: :get %></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %title Welcome to BACOMM!
    %meta{:content => "text/html;charset=utf-8", "http-equiv" => "Content-Type"}
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}
    %meta{:content => "width=device-width,initial-scale=1,maximum-scale=1,user-scalable=0", :name => "viewport"}
    = csrf_meta_tags
    = favicon_link_tag 'icon.png', :rel => "icon"
    %link{:href => "https://fonts.googleapis.com/css?family=Lato:300,300i,400,400i,700,700i", :rel => "stylesheet"}
    %link{:href => "https://fonts.googleapis.com/css?family=Montserrat:400,400i,500,500i,600,600i", :rel => "stylesheet"}
    %link{:href => "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css", :rel => "stylesheet"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
  %body
    = render 'layouts/header'
    = yield
    = render 'layouts/footer'

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html lang="en" class="login-body">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Login - Welcome to BACOMM!</title>
  <link href='https://fonts.googleapis.com/css?family=Lato:300,300i,400,400i,700,700i' rel='stylesheet'>
  <link href='https://fonts.googleapis.com/css?family=Montserrat:400,400i,500,500i,600,600i' rel='stylesheet'>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true  %>
</head>

<body class="login-body">
  <div class="ds-tbl">
    <div class="ds-tbl-cell">
      <%= yield %>
    </div>
  </div>
</body>

</html>